services:
  - type: web
    name: henze-trivia
    env: node
    region: oregon
    plan: free
    rootDir: web-app
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: ENFORCE_HTTPS
        value: false
